inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'spec/**/*'
  TargetRubyVersion: 2.5
Metrics/LineLength:
  Max: 99
Style/FileName:
  Enabled: false
Style/ModuleFunction:
  Enabled: false
Style/Encoding:
  Enabled: false
Documentation:
  Enabled: false
Metrics/MethodLength:
  Max: 15
