language: ruby
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head
  - jruby
gemfile:
  - gemfiles/activerecord_4.2.gemfile
  - gemfiles/activerecord_5.0.gemfile
  - gemfiles/activerecord_5.1.gemfile
  - gemfiles/activerecord_5.2.gemfile
  - gemfiles/activerecord_6.0.gemfile
  - gemfiles/activerecord_6.1.gemfile
  - gemfiles/activerecord_head.gemfile
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
bundler_args: --without local_development
before_install: gem install bundler -v 1.17.3
